# Generated by Django 4.1.1 on 2022-09-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('category', models.CharField(choices=[('M', 'Mobile'), ('T', 'Tablet'), ('C', 'Computer')], max_length=5)),
                ('label', models.CharField(choices=[('U', 'Used'), ('N', 'New'), ('R', 'Refurbished')], max_length=5)),
                ('slug', models.SlugField()),
                ('descreption', models.TextField()),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
            ],
        ),
    ]
